version: '3.8'

services:
  rabbitmq:
    image: rabbitmq:4.0.2-management
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: "admin"
      RABBITMQ_DEFAULT_PASS: "admin"
  
  mongodb:
    image: mongo:8.0.0
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: "admin"
      MONGO_INITDB_ROOT_PASSWORD: "admin"
  
  
  backend:
    image: weatherstation
    build:
      context: .
      dockerfile: WeatherStationBackend/Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - rabbitmq
      - mongodb
    environment:
      RABBITMQ_HOST: "rabbitmq"
      RABBITMQ_PORT: "5672"
  
  frontend:
    build:
      context: .
      dockerfile: weather-station-frontend/Dockerfile
    ports:
      - '3000:3000'
    depends_on:
      - backend
  